small fixes

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1053,17 +1053,15 @@ if [ $BRinterface = "CLI" ]; then
           remount_delete_subvols
         fi
         clean_unmount_in
-      elif [ $REPLY = "1" ]; then
-        while [ ! -f /mnt/target/fullbackup.tgz ]; do
-          echo -e "\n\e[00;36mEnter the path of the backup file\e[00m"
-	  read -p "Path:" BRfile
-	  if [ ! -f $BRfile ] || [ -z $BRfile ]; then
-            echo -e "\e[00;31mFile not found\e[00m"
-	  else
-            echo "==>Copying file..."
-            cp $BRfile "/mnt/target/fullbackup.tgz"                  
-       	  fi
-        done
+      elif [ $REPLY = "1" ]; then        
+        echo -e "\n\e[00;36mEnter the path of the backup file\e[00m"
+        read -p "Path:" BRfile
+        if [ ! -f $BRfile ] || [ -z $BRfile ]; then
+          echo -e "\e[00;31mFile not found\e[00m"
+	else
+          echo "==>Copying file..."
+          cp $BRfile "/mnt/target/fullbackup.tgz"                  
+	fi        
         break
       
       elif [ $REPLY = "2" ] || [ $REPLY = "3" ]; then
@@ -1097,17 +1095,18 @@ if [ $BRinterface = "CLI" ]; then
         echo -e "\e[00;31mPlease select a valid option from the list or enter Q to quit\e[00m"
       fi
     done
-    echo "==>Checking archive..."
-    tar tf /mnt/target/fullbackup.tgz 1>/dev/null
-    if [ "$?" = "0" ]; then
-      echo -e "\e[00;32mArchive appears OK\e[00m"
-    else 
-      echo -e "\e[00;31mError while reading file\e[00m"
-      rm /mnt/target/fullbackup.tgz
-    fi 
+    if [ -f /mnt/target/fullbackup.tgz ]; then
+      echo "==>Checking archive..."
+      tar tf /mnt/target/fullbackup.tgz 1>/dev/null
+      if [ "$?" = "0" ]; then
+        echo -e "\e[00;32mArchive appears OK\e[00m"
+      else 
+        echo -e "\e[00;31mError while reading file\e[00m"
+        rm /mnt/target/fullbackup.tgz
+      fi 
+    fi
   done
   
-
   echo -e "\n\e[00;32mSUMMARY\e[00m"
   show_summary
   echo " "
