add xz support

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -14,6 +14,16 @@ init_variables() {
 
 init_variables
 
+detect_filetype() {
+if [[  $BRfile == *.gz ]] || [[  $BRfile == *.tgz ]]; then
+  BRfiletype="gz"
+elif [[  $BRfile == *.xz ]]; then
+  BRfiletype="xz"
+else
+  BRfiletype="wrong"
+fi
+}
+
 detect_distro() {
   if [ -f /mnt/target/etc/yum.conf ]; then
     BRdistro="Fedora"
@@ -21,6 +31,14 @@ detect_distro() {
     BRdistro="Arch"
   elif [ -f /mnt/target/etc/apt/sources.list ]; then
     BRdistro="Debian"
+  fi
+}
+
+run_tar() {
+  if [ ${BRfiletype} = "gz" ]; then
+    tar xvpfz /mnt/target/fullbackup -C /mnt/target   2>&1 && echo SUCCESS  || echo WARNING  
+  elif [ ${BRfiletype} = "xz" ]; then
+    tar xvpfJ /mnt/target/fullbackup -C /mnt/target   2>&1 && echo SUCCESS  || echo WARNING  
   fi
 }
 
@@ -51,6 +69,13 @@ check_input() {
   if [ -n "$BRfile" ] && [ ! -f $BRfile ]; then
     echo -e "${BR_RED}File not found:${BR_NORM} $BRfile"
     BRSTOP=y
+  elif [ -n "$BRfile" ]; then
+    detect_filetype
+    if [ "$BRfiletype" = "wrong" ]; then
+      echo -e "${BR_RED}Invalid file type${BR_NORM}"
+      echo -e "${BR_CYAN}Supported file types: .gz .tgz .xz ${BR_NORM}"
+      BRSTOP=y
+    fi
   fi
 
   if [ -n "$BRfile" ] && [ -n "$BRurl" ]; then
@@ -441,8 +466,8 @@ remount_delete_subvols() {
   if [  "x$BRfsystem" = "xbtrfs" ] && [ "x$BRrootsubvol" = "xy" ]; then
     btrfs subvolume delete /mnt/target/$BRrootsubvolname
   fi
-  if [ -f /mnt/target/fullbackup.tgz ]; then
-    rm /mnt/target/fullbackup.tgz
+  if [ -f /mnt/target/fullbackup ]; then
+    rm /mnt/target/fullbackup
   fi
 
   echo -e "\n==>CLEANING AND UNMOUNTING"
@@ -551,8 +576,8 @@ clean_unmount_in() {
     fi
   fi
   
-  if [ -f /mnt/target/fullbackup.tgz ]; then
-    rm /mnt/target/fullbackup.tgz
+  if [ -f /mnt/target/fullbackup ]; then
+    rm /mnt/target/fullbackup
   fi
 
   echo "Unmounting $BRroot"
@@ -571,8 +596,8 @@ clean_unmount_in() {
 clean_unmount_out() {
   echo -e "\n==>CLEANING AND UNMOUNTING"
   cd ~ 
-  if [ -f /mnt/target/fullbackup.tgz ]; then
-    rm /mnt/target/fullbackup.tgz
+  if [ -f /mnt/target/fullbackup ]; then
+    rm /mnt/target/fullbackup
   fi
   umount /mnt/target/dev/pts  
   umount /mnt/target/proc
@@ -1193,39 +1218,39 @@ if [ $BRinterface = "CLI" ]; then
   
     if [ -n "$BRfile" ]; then
       echo "Copying file..."
-      cp $BRfile "/mnt/target/fullbackup.tgz"
+      cp $BRfile "/mnt/target/fullbackup"
     fi
 
     if [ -n "$BRurl" ]; then
       if [ -n "$BRusername" ]; then
-        wget --user=$BRusername --password=$BRpassword -O /mnt/target/fullbackup.tgz $BRurl --tries=2
+        wget --user=$BRusername --password=$BRpassword -O /mnt/target/fullbackup $BRurl --tries=2
         if [ "$?" -ne "0" ]; then
           echo -e "${BR_RED}Error downloading file${BR_NORM}"
           echo -e "${BR_RED}Wrong URL or network is down${BR_NORM}"
-          rm /mnt/target/fullbackup.tgz 2>/dev/null
+          rm /mnt/target/fullbackup 2>/dev/null
         fi
       else
-        wget -O /mnt/target/fullbackup.tgz $BRurl --tries=2
+        wget -O /mnt/target/fullbackup $BRurl --tries=2
         if [ "$?" -ne "0" ]; then
           echo -e "${BR_RED}Error downloading file${BR_NORM}"
           echo -e "${BR_RED}Wrong URL or network is down${BR_NORM}"
-          rm /mnt/target/fullbackup.tgz 2>/dev/null
+          rm /mnt/target/fullbackup 2>/dev/null
         fi
       fi
     fi
 
-    if [ -f /mnt/target/fullbackup.tgz ]; then
+    if [ -f /mnt/target/fullbackup ]; then
       echo "Checking archive..."
-      tar tf /mnt/target/fullbackup.tgz 1>/dev/null
+      tar tf /mnt/target/fullbackup 1>/dev/null
       if [ "$?" = "0" ]; then
         echo -e "${BR_GREEN}Archive appears OK${BR_NORM}"
       else 
         echo -e "${BR_RED}Error reading archive${BR_NORM}"
-        rm /mnt/target/fullbackup.tgz
+        rm /mnt/target/fullbackup
       fi 
     fi
 
-    while [ ! -f /mnt/target/fullbackup.tgz ]; do
+    while [ ! -f /mnt/target/fullbackup ]; do
       echo -e "\n${BR_CYAN}Select an option or enter Q to quit${BR_NORM}"
       select c in "File" "URL" "Protected URL"; do
         if [ $REPLY = "q" ] || [ $REPLY = "Q" ]; then
@@ -1237,12 +1262,17 @@ if [ $BRinterface = "CLI" ]; then
           clean_unmount_in
         elif [ $REPLY = "1" ]; then        
           echo -e "\n${BR_CYAN}Enter the path of the backup file${BR_NORM}"
-          read -p "Path:" BRfile
+          read -p "Path:" BRfile          
           if [ ! -f $BRfile ] || [ -z $BRfile ]; then
             echo -e "${BR_RED}File not found${BR_NORM}"
-	  else
-            echo "Copying file..."
-            cp $BRfile "/mnt/target/fullbackup.tgz"                  
+      	  else
+            detect_filetype      
+            if [ $BRfiletype = "gz" ] || [ $BRfiletype = "xz" ]; then
+              echo "Copying file..."
+              cp $BRfile "/mnt/target/fullbackup"
+            else
+               echo -e "${BR_RED}Invalid file type${BR_NORM}"
+            fi 
 	  fi        
           break
       
@@ -1253,33 +1283,33 @@ if [ $BRinterface = "CLI" ]; then
           if [ $REPLY = "3" ]; then
 	    read -p "USERNAME: " BRusername
             read -p "PASSWORD: " BRpassword
-	    wget --user=$BRusername --password=$BRpassword  -O /mnt/target/fullbackup.tgz $BRurl --tries=2
+	    wget --user=$BRusername --password=$BRpassword  -O /mnt/target/fullbackup $BRurl --tries=2
             if [ "$?" -ne "0" ]; then
               echo -e "${BR_RED}Error downloading file${BR_NORM}"
               echo -e "${BR_RED}Wrong URL or network is down${BR_NORM}"
-	      rm /mnt/target/fullbackup.tgz 2>/dev/null
+	      rm /mnt/target/fullbackup 2>/dev/null
             fi
 	    break
           fi
-          wget -O /mnt/target/fullbackup.tgz $BRurl --tries=2
+          wget -O /mnt/target/fullbackup $BRurl --tries=2
           if [ "$?" -ne "0" ]; then
             echo -e "${BR_RED}Error downloading file${BR_NORM}"
             echo -e "${BR_RED}Wrong URL or network is down${BR_NORM}"
-	    rm /mnt/target/fullbackup.tgz 2>/dev/null
+	    rm /mnt/target/fullbackup 2>/dev/null
           fi
           break
         else
           echo -e "${BR_RED}Please select a valid option from the list or enter Q to quit${BR_NORM}"
         fi
       done
-      if [ -f /mnt/target/fullbackup.tgz ]; then
+      if [ -f /mnt/target/fullbackup ]; then
         echo "Checking archive..."
-        tar tf /mnt/target/fullbackup.tgz 1>/dev/null
+        tar tf /mnt/target/fullbackup 1>/dev/null
         if [ "$?" = "0" ]; then
           echo -e "${BR_GREEN}Archive appears OK${BR_NORM}"
         else 
           echo -e "${BR_RED}Error reading archive${BR_NORM}"
-          rm /mnt/target/fullbackup.tgz
+          rm /mnt/target/fullbackup
         fi 
       fi
     done
@@ -1323,7 +1353,7 @@ if [ $BRinterface = "CLI" ]; then
     if [ $BRmode = "Restore" ]; then
       echo -e "\n==>EXTRACTING"
       sleep 1
-      tar xvpfz /mnt/target/fullbackup.tgz -C /mnt/target   2>&1 && echo SUCCESS  || echo WARNING  
+      run_tar
     elif [ $BRmode = "Transfer" ]; then
       echo -e "\n==>TRANSFERING"
       sleep 1
@@ -1674,43 +1704,43 @@ Press OK to continue."  25 80
   if [ $BRmode = "Restore" ]; then
     if [ -n "$BRfile" ]; then
       ( echo "Copying file..." 
-      cp "${BRfile[@]}" "/mnt/target/fullbackup.tgz" ) | dialog  --progressbox  4 30
+      cp "${BRfile[@]}" "/mnt/target/fullbackup" ) | dialog  --progressbox  4 30
     fi
 
     if [ -n "$BRurl" ]; then
       if [ -n "$BRusername" ]; then
-        ( wget --user=$BRusername --password=$BRpassword -O /mnt/target/fullbackup.tgz $BRurl --tries=2 2>&1
+        ( wget --user=$BRusername --password=$BRpassword -O /mnt/target/fullbackup $BRurl --tries=2 2>&1
         if [ "$?" -ne "0" ]; then
           echo "Error downloading file"
           echo "Wrong URL or network is down"
           sleep 2
-          rm /mnt/target/fullbackup.tgz 2>/dev/null
+          rm /mnt/target/fullbackup 2>/dev/null
         fi ) | dialog --title "Downloading" --progressbox  30 70
       else
-        ( wget -O /mnt/target/fullbackup.tgz $BRurl --tries=2 2>&1
+        ( wget -O /mnt/target/fullbackup $BRurl --tries=2 2>&1
         if [ "$?" -ne "0" ]; then
           echo "Error downloading file"
           echo "Wrong URL or network is down"
           sleep 2
-          rm /mnt/target/fullbackup.tgz 2>/dev/null
+          rm /mnt/target/fullbackup 2>/dev/null
         fi ) | dialog --title "Downloading" --progressbox 30 70
       fi
     fi
 
-    if [ -f /mnt/target/fullbackup.tgz ]; then
+    if [ -f /mnt/target/fullbackup ]; then
       ( echo "Checking archive..." 
-        tar tf /mnt/target/fullbackup.tgz > /dev/null 2>&1
+        tar tf /mnt/target/fullbackup > /dev/null 2>&1
         if [ "$?" = "0" ]; then
           echo  "Archive appears OK"
           sleep 2
         else 
           echo  "Error reading archive"
           sleep 2
-          rm /mnt/target/fullbackup.tgz 2>&1
+          rm /mnt/target/fullbackup 2>&1
         fi ) | dialog  --progressbox 4 30
     fi 
 
-    while [ ! -f /mnt/target/fullbackup.tgz ]; do
+    while [ ! -f /mnt/target/fullbackup ]; do
       REPLY=$(dialog  --cancel-label Quit --menu "Select backup file. Choose an option:" 13 50 13  File "local file" URL "remote file" Protected "protected server" 2>&1 1>&3)
       if [ $? = "1" ]; then
         if [  "x$BRfsystem" = "xbtrfs" ] && [ "x$BRrootsubvol" = "xy" ]; then
@@ -1724,8 +1754,14 @@ Press OK to continue."  25 80
             echo "File not found" | dialog --title "Error" --progressbox  3 18
             sleep 2
           else
-            ( echo "Copying file..."
-            cp "${BRfile[@]}" "/mnt/target/fullbackup.tgz" ) | dialog  --progressbox 4 30
+            detect_filetype
+            if [ $BRfiletype = "gz" ] || [ $BRfiletype = "xz" ]; then
+              ( echo "Copying file..."
+              cp "${BRfile[@]}" "/mnt/target/fullbackup" ) | dialog  --progressbox 4 30
+            else
+               echo "Invalid file type" | dialog --title "Error" --progressbox  3 21
+               sleep 2
+             fi
           fi
   
       elif [ $REPLY = "URL" ] || [ $REPLY = "Protected" ]; then
@@ -1733,34 +1769,34 @@ Press OK to continue."  25 80
         if [  $REPLY = "Protected" ]; then
           BRusername=$(dialog --no-cancel --inputbox "Username:" 8 50 2>&1 1>&3)
           BRpassword=$(dialog --no-cancel --insecure --passwordbox "Password:" 8 50 2>&1 1>&3)
-          ( wget --user=$BRusername --password=$BRpassword  -O /mnt/target/fullbackup.tgz $BRurl --tries=2 2>&1
+          ( wget --user=$BRusername --password=$BRpassword  -O /mnt/target/fullbackup $BRurl --tries=2 2>&1
           if [ "$?" -ne "0" ]; then
             echo  "Error downloading file"
             echo "Wrong URL or network is down"
 	    sleep 2
-            rm /mnt/target/fullbackup.tgz 2>/dev/null
+            rm /mnt/target/fullbackup 2>/dev/null
           fi ) | dialog --title "Downloading" --progressbox  30 70
 
         elif [ $REPLY = "URL" ]; then
-          ( wget -O /mnt/target/fullbackup.tgz $BRurl --tries=2 2>&1
+          ( wget -O /mnt/target/fullbackup $BRurl --tries=2 2>&1
           if [ "$?" -ne "0" ]; then
             echo  "Error downloading file"
             echo "Wrong URL or network is down"
             sleep 2
-            rm /mnt/target/fullbackup.tgz 2>/dev/null
+            rm /mnt/target/fullbackup 2>/dev/null
           fi ) | dialog --title "Downloading" --progressbox 30 70
         fi 
       fi
-      if [ -f /mnt/target/fullbackup.tgz ]; then
+      if [ -f /mnt/target/fullbackup ]; then
         ( echo "Checking archive..." 
-          tar tf /mnt/target/fullbackup.tgz > /dev/null 2>&1
+          tar tf /mnt/target/fullbackup > /dev/null 2>&1
           if [ "$?" = "0" ]; then
             echo  "Archive appears OK"
             sleep 2
           else 
             echo  "Error reading archive"
             sleep 2
-            rm /mnt/target/fullbackup.tgz 2>&1
+            rm /mnt/target/fullbackup 2>&1
           fi ) | dialog  --progressbox 4 30
       fi
     done
@@ -1793,7 +1829,7 @@ Press Yes to continue, or No to abort." 19 60
   fi  
 
   if [ $BRmode = "Restore" ]; then
-    ( tar xvpfz /mnt/target/fullbackup.tgz -C /mnt/target   2>&1 && echo SUCCESS  || echo WARNING ) | dialog --title "EXTRACTING" --progressbox  30 90
+    run_tar 2>&1 | dialog --title "EXTRACTING" --progressbox  30 90
     sleep 2
   elif [ $BRmode = "Transfer" ]; then
     run_rsync  2>&1 | dialog --title  "TRANSFERING" --progressbox 30 90
