Fixed if

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -215,19 +215,20 @@ if [ -n "$file" ]; then
   cp $file "/media/target/fullbackup.tgz"
 elif [ -n "$url" ]; then
   if [ -n "$USERNAME" ]; then
-   wget --user=$USERNAME --password=$PASSWORD -O /media/target/fullbackup.tgz  $url --tries=2
+    wget --user=$USERNAME --password=$PASSWORD -O /media/target/fullbackup.tgz $url --tries=2
+    if [ "$?" -ne "0" ]; then
+      echo "ERROR"
+      rm /media/target/fullbackup.tgz
+    fi
+  fi
+else
+  wget -O /media/target/fullbackup.tgz $url --tries=2
   if [ "$?" -ne "0" ]; then
     echo "ERROR"
     rm /media/target/fullbackup.tgz
   fi
-  else
-    wget -O /media/target/fullbackup.tgz $url --tries=2
- if [ "$?" -ne "0" ]; then
-    echo "ERROR"
-    rm /media/target/fullbackup.tgz
-  fi
-  fi
 fi
+
 
 while [ ! -f /media/target/fullbackup.tgz ]; do
     
