better error handling while mounting

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -166,17 +166,7 @@ mount_all() {
   echo -e "\n==>MOUNTING $BRroot (/)"
   mount $BRroot /mnt/target
   if [ "$?" -ne "0" ]; then
-    echo -e "\n==>CLEANING"
-    cd ~
-    sleep 1
-    if [ "$(ls -A /mnt/target)" ]; then
-      echo "/mnt/target is not empty"
-    else
-      sleep 1
-      rm -r /mnt/target 2>&1 && echo SUCCESS  || echo FAILED 
-    fi
-    echo -e "\e[00;31mError while mounting partitions\e[00m"
-    exit
+    touch /tmp/stop
   else
     echo SUCCESS
   fi
@@ -186,24 +176,7 @@ mount_all() {
     mkdir /mnt/target/home 2>&1 
     mount $BRhome /mnt/target/home
     if [ "$?" -ne "0" ]; then
-      echo -e "\n==>CLEANING AND UNMOUNTING"
-      cd ~
-      sleep 1
-      if [ "$(ls -A /mnt/target/home)" ]; then
-        echo "/mnt/target/home is not empty"
-      else
-        rm -r /mnt/target/home
-      fi
-      echo "Unmounting $BRroot"
-      umount $BRroot 2>&1 && echo SUCCESS  || echo FAILED 
-      if [ "$(ls -A /mnt/target)" ]; then
-        echo "/mnt/target is not empty"
-      else
-        sleep 1
-        rm -r /mnt/target
-      fi
-      echo -e "\e[00;31mError while mounting partitions\e[00m"
-      exit
+      touch /tmp/stop
     else
       echo SUCCESS
     fi
@@ -214,33 +187,7 @@ mount_all() {
     mkdir /mnt/target/boot 2>&1
     mount $BRboot /mnt/target/boot
     if [ "$?" -ne "0" ]; then
-      echo -e "\n==>CLEANING AND UNMOUNTING"
-      cd ~
-      sleep 1
-      if [ -n "$BRhome" ]; then  
-        echo "Unmounting $BRhome"
-        umount $BRhome
-        if [ "$(ls -A /mnt/target/home)" ]; then
-          echo "/mnt/target/home is not empty"
-        else
-          rm -r /mnt/target/home
-        fi
-      fi
-      if [ "$(ls -A /mnt/target/boot)" ]; then
-        echo "/mnt/target/boot is not empty"
-      else
-        rm -r /mnt/target/boot
-      fi
-      echo "Unmounting $BRroot"
-      umount $BRroot 2>&1 && echo SUCCESS  || echo FAILED 
-      if [ "$(ls -A /mnt/target)" ]; then
-        echo "/mnt/target is not empty"
-      else
-        sleep 1
-        rm -r /mnt/target
-      fi
-      echo -e "\e[00;31mError while mounting partitions\e[00m"
-      exit
+      touch /tmp/stop
     else
       echo SUCCESS
     fi
@@ -525,7 +472,36 @@ unmount_only_in_subvol() {
     else
       echo "SUCCESS"
     fi
-}  
+}
+
+clean_unmount_error() {
+  echo -e "\n==>CLEANING AND UNMOUNTING"
+  cd ~
+  if [ -n "$BRhome" ]; then
+    umount $BRhome 2> /dev/null
+    if [ "$(ls -A /mnt/target/home)" ]; then
+      echo "/mnt/target/home is not empty"
+    else
+      rm -r /mnt/target/home
+    fi
+  fi
+  if [ -n "$BRboot" ]; then
+    umount $BRboot 2> /dev/null
+    if [ "$(ls -A /mnt/target/boot)" ]; then
+      echo "/mnt/target/boot is not empty"
+    else
+      rm -r /mnt/target/boot
+    fi
+  fi
+  umount $BRroot 2> /dev/null
+  if [ "$(ls -A /mnt/target)" ]; then
+    echo "/mnt/target is not empty"
+  else
+    sleep 1
+    rm -r /mnt/target 2>&1 && echo SUCCESS || echo FAILED
+  fi
+  exit
+}
 
 clean_unmount_in() {
   echo -e "\n==>CLEANING AND UNMOUNTING"
@@ -1061,6 +1037,12 @@ if [ $BRinterface = "CLI" ]; then
   check_input
   mount_all
 
+  if [ -f /tmp/stop ]; then
+    rm  /tmp/stop
+    echo -e "\e[00;31mError while mounting partitions\e[00m"
+    clean_unmount_error
+  fi
+
   BRfsystem=(`df -T | grep $BRroot | awk '{ print $2}'`)
   BRfsize=(`lsblk -d -n -o size 2> /dev/null $BRroot`)
 
@@ -1521,7 +1503,13 @@ Press OK to continue."  25 80
   fi
 
   check_input
-  mount_all
+  mount_all 2>&1 | dialog --title "Mounting" --progressbox 30 70
+
+  if [ -f /tmp/stop ]; then
+    rm  /tmp/stop
+    echo -e "\e[00;31mError while mounting partitions\e[00m"
+    clean_unmount_error
+  fi
 
   BRfsystem=(`df -T | grep $BRroot | awk '{ print $2}'`)
   BRfsize=(`lsblk -d -n -o size 2> /dev/null $BRroot`)
