Added -O in wget again, now if returns error file will deleted

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -223,11 +223,18 @@ if [ -n "$file" ]; then
   cp $file "/media/target/fullbackup.tgz"
 elif [ -n "$url" ]; then
   if [ -n "$USERNAME" ]; then
-    cd /media/target
-    wget --user=$USERNAME --password=$PASSWORD  $url --tries=2
+   wget --user=$USERNAME --password=$PASSWORD -O /media/target/fullbackup.tgz  $url --tries=2
+  if [ "$?" -ne "0" ]; then
+    echo "ERROR"
+    rm /media/target/fullbackup.tgz
+  fi
   else
     cd /media/target
-    wget  $url --tries=2
+    wget  -O /media/target/fullbackup.tgz $url --tries=2
+ if [ "$?" -ne "0" ]; then
+    echo "ERROR"
+    rm /media/target/fullbackup.tgz
+  fi
   fi
 fi
 
@@ -269,13 +276,19 @@ while [ ! -f /media/target/fullbackup.tgz ]; do
 	read -p "Enter the username: " USERNAME
 	read -sp "Enter the password: " PASSWORD
 	echo " "
-        cd /media/target
-	wget --user=$USERNAME --password=$PASSWORD $url --tries=2
+	wget --user=$USERNAME --password=$PASSWORD  -O /media/target/fullbackup.tgz $url --tries=2
+         if [ "$?" -ne "0" ]; then
+    echo "ERROR"
+    rm /media/target/fullbackup.tgz
+         fi
 	echo -e "\nDownloaded file: `pwd`/$file"
 	break
       fi
-      cd /media/target
-      wget $url --tries=2
+      wget -O /media/target/fullbackup.tgz $url --tries=2
+       if [ "$?" -ne "0" ]; then
+    echo "ERROR"
+    rm /media/target/fullbackup.tgz 
+       fi
       echo -e "\nDownloaded file: `pwd`/$file"
       break
     else
