Formatted text and deleted some lines

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -11,18 +11,15 @@ while getopts "r:s:b:h:g:f:u:n:p:y" arg; do
   case $arg in
     r) 
       root=$OPTARG
-      #fsystem=(`blkid -s TYPE -o value $root`)
     ;;
     s) 
       swap=$OPTARG
     ;;
     b) 
       boot=$OPTARG
-      #bootfsystem=(`blkid -s TYPE -o value $boot`)
     ;;
     h) 
       home=$OPTARG
-      #homefsystem=(`blkid -s TYPE -o value $home`)
     ;;
     g) 
       grub=$OPTARG
@@ -128,9 +125,7 @@ if [ -z "$home" ]; then
       exit
     elif [[ $REPLY = [0-9]* ]] && [ $REPLY -gt 0 ] && [ $REPLY -le ${#list[@]} ]; then
       home=(`echo $c | awk '{ print $1 }'`)
-      #homefsystem=(`echo $c | awk '{ print $2 }'`)
       echo "You selected $home as your home partition" 
-      #echo "The filesystem is $homefsystem" 
       break
     elif [ $REPLY = "c" ] || [ $REPLY = "C" ]; then
       echo "No separate home"
@@ -149,9 +144,7 @@ if [ -z "$boot" ]; then
       exit
     elif [[ $REPLY = [0-9]* ]] && [ $REPLY -gt 0 ] && [ $REPLY -le ${#list[@]} ]; then
       boot=(`echo $c | awk '{ print $1 }'`)
-      #bootfsystem=(`echo $c | awk '{ print $2 }'`)
       echo "You selected $boot as your boot partition" 
-      #echo "The filesystem is $bootfsystem" 
       break
     elif [ $REPLY = "c" ] || [ $REPLY = "C" ]; then
       echo "No separate boot"
@@ -228,8 +221,7 @@ elif [ -n "$url" ]; then
     rm /media/target/fullbackup.tgz
   fi
   else
-    cd /media/target
-    wget  -O /media/target/fullbackup.tgz $url --tries=2
+    wget -O /media/target/fullbackup.tgz $url --tries=2
  if [ "$?" -ne "0" ]; then
     echo "ERROR"
     rm /media/target/fullbackup.tgz
@@ -243,18 +235,18 @@ while [ ! -f /media/target/fullbackup.tgz ]; do
   select c in "File" "URL" "Protected URL"; do
     if [ $REPLY = "q" ] || [ $REPLY = "Q" ]; then
       echo "Now quiting"
-        cd ~ 
-    if [ -n "$home" ]; then
-    umount  $home
-    rm -r /media/target/home
-    fi
-    if [ -n "$boot" ]; then
-    umount  $boot
-    rm -r /media/target/boot
-    fi
-  umount $root 
-  sleep 1
-  rm  -r /media/target 2>&1 && echo SUCCESS  || echo FAILED 
+      cd ~ 
+      if [ -n "$home" ]; then
+	umount  $home
+	rm -r /media/target/home
+      fi
+      if [ -n "$boot" ]; then
+	umount  $boot
+	rm -r /media/target/boot
+      fi
+      umount $root 
+      sleep 1
+      rm  -r /media/target 2>&1 && echo SUCCESS  || echo FAILED 
       exit      
     elif [ $REPLY = "1" ]; then
       while [ ! -f /media/target/fullbackup.tgz ]; do
@@ -276,19 +268,17 @@ while [ ! -f /media/target/fullbackup.tgz ]; do
 	read -sp "Enter the password: " PASSWORD
 	echo " "
 	wget --user=$USERNAME --password=$PASSWORD  -O /media/target/fullbackup.tgz $url --tries=2
-         if [ "$?" -ne "0" ]; then
-    echo "ERROR"
-    rm /media/target/fullbackup.tgz
-         fi
-#	echo -e "\nDownloaded file: `pwd`/$file"
+        if [ "$?" -ne "0" ]; then
+	  echo "ERROR"
+	  rm /media/target/fullbackup.tgz
+        fi
 	break
       fi
       wget -O /media/target/fullbackup.tgz $url --tries=2
-       if [ "$?" -ne "0" ]; then
-    echo "ERROR"
-    rm /media/target/fullbackup.tgz 
-       fi
-#      echo -e "\nDownloaded file: `pwd`/$file"
+      if [ "$?" -ne "0" ]; then
+	echo "ERROR"
+	rm /media/target/fullbackup.tgz 
+      fi
       break
     else
       echo "Please select a valid option from the list or enter Q to quit"
