added tar file check

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1007,7 +1007,7 @@ if [ $BRinterface = "CLI" ]; then
   fi
 
   echo -e "\n==>GETTING TAR IMAGE"
-
+  
   if [ -n "$BRfile" ]; then
     echo "==>Copying file..."
     cp $BRfile "/mnt/target/fullbackup.tgz"
@@ -1029,6 +1029,16 @@ if [ $BRinterface = "CLI" ]; then
     fi
   fi
 
+  if [ -f /mnt/target/fullbackup.tgz ]; then
+    echo "==>Checking file..."
+    tar tf /mnt/target/fullbackup.tgz 1>/dev/null
+    if [ "$?" = "0" ]; then
+      echo -e "\e[00;32mFile appears OK\e[00m"
+    else 
+      echo -e "\e[00;31mError while reading file\e[00m"
+      rm /mnt/target/fullbackup.tgz
+    fi 
+  fi
 
   while [ ! -f /mnt/target/fullbackup.tgz ]; do
     echo -e "\n\e[00;36mSelect an option or enter Q to quit\e[00m"
@@ -1048,7 +1058,7 @@ if [ $BRinterface = "CLI" ]; then
             echo -e "\e[00;31mFile not found\e[00m"
 	  else
             echo "==>Copying file..."
-            cp $BRfile "/mnt/target/fullbackup.tgz"
+            cp $BRfile "/mnt/target/fullbackup.tgz"                  
        	  fi
         done
         break
@@ -1078,7 +1088,16 @@ if [ $BRinterface = "CLI" ]; then
         echo -e "\e[00;31mPlease select a valid option from the list or enter Q to quit\e[00m"
       fi
     done
+    echo "==>Checking file..."
+    tar tf /mnt/target/fullbackup.tgz 1>/dev/null
+    if [ "$?" = "0" ]; then
+      echo -e "\e[00;32mFile appears OK\e[00m"
+    else 
+      echo -e "\e[00;31mError while reading file\e[00m"
+      rm /mnt/target/fullbackup.tgz
+    fi 
   done
+  
 
   echo -e "\n\e[00;32mSUMMARY\e[00m"
   show_summary
@@ -1435,6 +1454,19 @@ Press OK to continue."  20 100
     fi
   fi
 
+  ( if [ -f /mnt/target/fullbackup.tgz ]; then
+      echo "==>Checking file..." 
+      tar tf /mnt/target/fullbackup.tgz 2>&1 1>/dev/null
+      if [ "$?" = "0" ]; then
+        echo  "File appears OK"
+        sleep 2
+      else 
+        echo  "Error while reading file"
+        sleep 2
+        rm /mnt/target/fullbackup.tgz 2>&1
+      fi 
+  fi ) | dialog --progressbox "Working..." 30 70
+
   while [ ! -f /mnt/target/fullbackup.tgz ]; do
     REPLY=$(dialog  --cancel-label Quit --menu "Select backup file. Choose an option." 13 50 13  File "local file" URL "remote file" Protected "protected server" 2>&1 1>&3)
     if [ $? = "1" ]; then
@@ -1474,6 +1506,16 @@ Press OK to continue."  20 100
         fi ) | dialog --progressbox "Downloading file..." 30 70
       fi 
     fi
+      ( echo "==>Checking file..." 
+      tar tf /mnt/target/fullbackup.tgz 2>&1 1>/dev/null
+      if [ "$?" = "0" ]; then
+        echo  "File appears OK"
+        sleep 2
+      else 
+        echo  "Error while reading file"
+        sleep 2
+        rm /mnt/target/fullbackup.tgz 2>&1
+      fi ) | dialog --progressbox "Working..." 30 70
   done
 
   if [ -z $def ]; then
